services:
  nextcloud-cron:
    container_name: nextcloud-cron
    depends_on:
      nextcloud-postgres:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
    entrypoint: /cron.sh
    image: nextcloud:30.0.6-fpm
    restart: always
    volumes:
    - ./data/nc_data:/var/www/html:z
  nextcloud-fpm:
    entrypoint: ["/bin/bash", "-c" , "apt update && apt install smbclient libsmbclient-dev -y && pecl install smbclient && docker-php-ext-enable smbclient ; /entrypoint.sh php-fpm"]
    container_name: nextcloud-fpm
    depends_on:
      nextcloud-postgres:
        condition: service_healthy
      nextcloud-redis:
        condition: service_started
    env_file:
    - ./nextcloud.env
    image: nextcloud:30.0.6-fpm
    restart: unless-stopped
    volumes:
    - ./data/nc_data:/var/www/html:z
  nextcloud-nginx:
    container_name: nextcloud-nginx
    depends_on:
      nextcloud-fpm:
        condition: service_started
    env_file:
    - ./nextcloud.env
    ports:
    - 80:80
    - 443:443
    expose:
      - 443
      - 80
    restart: unless-stopped
    volumes:
    - ./data/nc_data:/var/www/html:z
    image: ghcr.io/netzint/nextcloud-ngnix:latest
  nextcloud-postgres:
    container_name: nextcloud-postgres
    env_file:
    - ./nextcloud.env
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -U nextcloud -d nextcloud -h 127.0.0.1 || exit 1
      timeout: 5s
    image: postgres:16.8
    restart: unless-stopped
    volumes:
    - ./data/nc_postgres:/var/lib/postgresql/data:Z
  nextcloud-redis:
    command:
    - redis-server
    - --appendonly
    - 'yes'
    container_name: nextcloud-redis
    env_file:
    - ./nextcloud.env
    image: redis:7.4.2
    restart: unless-stopped
    volumes:
    - ./data/nc_redis:/data
